# Generated by Django 4.1.3 on 2022-11-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
