# Generated by Django 4.1.3 on 2022-11-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_data',
        ),
    ]
